# Confidence thresholds
CONF_MIN = 0.0
CONF_LOW_THRESHOLD = 1.0
CONF_MID_HIGH_THRESHOLD = 7.0
CONF_MAX = 10.0

# TTV thresholds
TTV_SLOW_THRESHOLD = 5.0
TTV_MID_THRESHOLD = 7.0
TTV_MAX = 10.0
TTV_MIN = 0.0