"""Final fix: Add missing columns and Decision table

Revision ID: 94647648165a
Revises: e95b1ece6168
Create Date: 2025-12-03 19:14:55.740293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94647648165a'
down_revision = 'e95b1ece6168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. ADD NEW TABLE: Decision (Deze is nieuw en moet worden aangemaakt)
    op.create_table('decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_feature', sa.TEXT(), nullable=False), 
    sa.Column('id_company', sa.Integer(), nullable=False), 
    sa.Column('decision_type', sa.String(length=100), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_feature'], ['public.features_ideas.id_feature'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_company'], ['public.company.id_company'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    
    # 2. ADD MISSING COLUMN: confidence_impact aan Evidence
    # Deze kolom is noodzakelijk en ontbrak in de database (oorzaak van de UndefinedColumn fout).
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence_impact', sa.NUMERIC(), nullable=True))

    # 3. VERWIJDEREN VAN ALLE ONNODIGE COMMANDO'S:
    # We verwijderen alle 'op.create_table(roadmap)' en alle
    # op.drop_column / op.add_column commando's voor bestaande tabellen
    # (features_ideas, milestone, profile, project, etc.) die de database
    # zouden herschrijven of breken.
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # De downgrade functie moet de upgrade ongedaan maken:
    # 1. Drop de Decision tabel.
    op.drop_table('decision', schema='public')
    
    # 2. Verwijder de toegevoegde kolom.
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_column('confidence_impact')
        
    # ### end Alembic commands ###