"""Final cleanup and TTV limits

Revision ID: a6b03e94a4b4
Revises: 94647648165a
Create Date: 2025-12-12 18:42:34.167541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6b03e94a4b4'
down_revision = '94647648165a'
branch_labels = None
depends_on = None

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. TtV Limits terugverplaatsen naar 'features_ideas'
    with op.batch_alter_table('features_ideas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ttm_low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ttm_high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ttbv_low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ttbv_high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # 2. TtV Limits verwijderen uit de 'project' tabel
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('ttbv_high_limit')
        batch_op.drop_column('ttbv_low_limit')
        batch_op.drop_column('ttm_high_limit')
        batch_op.drop_column('ttm_low_limit')
        
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. TtV Limits toevoegen aan de 'project' tabel
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ttm_low_limit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ttm_high_limit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ttbv_low_limit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ttbv_high_limit', sa.Float(), nullable=True))

    # 2. TtV Limits verwijderen uit de 'features_ideas' tabel
    with op.batch_alter_table('features_ideas', schema=None) as batch_op:
        batch_op.drop_column('ttm_low')
        batch_op.drop_column('ttm_high')
        batch_op.drop_column('ttbv_low')
        batch_op.drop_column('ttbv_high')
        
    # ### end Alembic commands ###
