"""Update Features_ideas with ROI, TTV, Confidence fields

Revision ID: cd74699c3535
Revises:
Create Date: 2025-11-24 17:14:27.636345

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cd74699c3535"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("confidence_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id_project", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("id_company", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("project_name", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("createdat", sa.DateTime(), nullable=True))
        # batch_op.drop_constraint(batch_op.f('confidence_history_id_feature_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(
            None, "company", ["id_company"], ["id_company"], referent_schema="public"
        )
        batch_op.drop_column("id_confidence")
        # batch_op.drop_column('id_feature')
        batch_op.drop_column("old_value")
        batch_op.drop_column("new_value")

    with op.batch_alter_table("decision_history", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "name_feature",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("id_company", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("id_project", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "gains",
                sa.NUMERIC(precision=10, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "costs",
                sa.NUMERIC(precision=10, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "churn_opex",
                sa.NUMERIC(precision=10, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "opp_cost",
                sa.NUMERIC(precision=10, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "market_value",
                sa.NUMERIC(precision=10, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "business_value",
                sa.NUMERIC(precision=10, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "validation_stage",
                sa.VARCHAR(length=100),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "quality_score",
                sa.NUMERIC(precision=5, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "createdat",
                postgresql.TIMESTAMP(),
                server_default=sa.text("now()"),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.alter_column(
            "id_feature", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.drop_constraint(
            batch_op.f("decision_history_id_profile_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("decision_history_id_feature_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "features_ideas_id_company_fkey",
            "company",
            ["id_company"],
            ["id_company"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "features_ideas_id_project_fkey",
            "project",
            ["id_project"],
            ["id_project"],
            ondelete="SET NULL",
        )
        batch_op.drop_column("id_profile")
        batch_op.drop_column("id_decision")
        batch_op.drop_column("decision_text_yes_no")

    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id_project", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("name_feature", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("revenue", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("cost_savings", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("investment_hours", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("opex_hours", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("other_costs", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("horizon", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("expected_profit", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("roi_percent", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("ttm_weeks", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("ttbv_weeks", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("ttv_weeks", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("quality_score", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("createdat", sa.DateTime(), nullable=True))
        batch_op.alter_column(
            "id_feature", existing_type=sa.INTEGER(), type_=sa.String(), nullable=False
        )
        batch_op.alter_column("id_company", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_constraint(
            batch_op.f("evidence_id_feature_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("evidence_id_company_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "company", ["id_company"], ["id_company"], referent_schema="public"
        )
        batch_op.create_foreign_key(
            None, "project", ["id_project"], ["id_project"], referent_schema="public"
        )
        batch_op.drop_column("id_evidence")
        batch_op.drop_column("confidence_impact")
        batch_op.drop_column("type")
        batch_op.drop_column("source")
        batch_op.drop_column("attachment_url")

    with op.batch_alter_table("features_ideas", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "project_name",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.alter_column(
            "id_project", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.drop_constraint(
            batch_op.f("features_ideas_id_company_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("features_ideas_id_project_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "project_id_company_fkey", "company", ["id_company"], ["id_company"]
        )
        batch_op.drop_column("opp_cost")
        batch_op.drop_column("market_value")
        batch_op.drop_column("name_feature")
        batch_op.drop_column("validation_stage")
        batch_op.drop_column("churn_opex")
        batch_op.drop_column("costs")
        batch_op.drop_column("quality_score")
        batch_op.drop_column("business_value")
        batch_op.drop_column("id_feature")
        batch_op.drop_column("gains")

    with op.batch_alter_table("milestone", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id_project", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("quarter", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("team_size", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("sprint_capacity", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("budget_allocation", sa.Integer(), nullable=False)
        )
        batch_op.add_column(sa.Column("createdat", sa.DateTime(), nullable=True))
        batch_op.alter_column(
            "id_roadmap", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.drop_constraint(
            batch_op.f("milestone_id_roadmap_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None,
            "project",
            ["id_project"],
            ["id_project"],
            referent_schema="public",
            ondelete="CASCADE",
        )
        batch_op.drop_column("name")
        batch_op.drop_column("id_milestone")
        batch_op.drop_column("goal")
        batch_op.drop_column("status")
        batch_op.drop_column("start_date")
        batch_op.drop_column("end_date")

    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.add_column(sa.Column("company_name", sa.String(), nullable=False))
        batch_op.alter_column(
            "id_company", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.drop_constraint(batch_op.f("profile_email_key"), type_="unique")
        batch_op.drop_constraint(
            batch_op.f("profile_id_company_fkey"), type_="foreignkey"
        )
        batch_op.drop_column("id_profile")
        batch_op.drop_column("name")
        batch_op.drop_column("role")
        batch_op.drop_column("email")
        batch_op.drop_column("createdat")

    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "id_profile",
                sa.INTEGER(),
                server_default=sa.text("nextval('profile_id_profile_seq'::regclass)"),
                autoincrement=True,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "email", sa.VARCHAR(length=255), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "role", sa.VARCHAR(length=100), autoincrement=False, nullable=True
            )
        )
        batch_op.create_unique_constraint(
            "profile_email_key",
            ["email"],
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.drop_constraint(
            batch_op.f("project_id_company_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "profile_id_company_fkey",
            "company",
            ["id_company"],
            ["id_company"],
            ondelete="SET NULL",
        )
        batch_op.drop_column("id_project")
        batch_op.drop_column("project_name")

    with op.batch_alter_table("roadmap", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id_profile", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("name", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("email", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("role", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("id_company", sa.Integer(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("roadmap_id_project_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "company", ["id_company"], ["id_company"], referent_schema="public"
        )
        batch_op.drop_column("team_size")
        batch_op.drop_column("quarter")
        batch_op.drop_column("budget_allocation")
        batch_op.drop_column("id_roadmap")
        batch_op.drop_column("id_project")
        batch_op.drop_column("sprint_capacity")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roadmap", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "sprint_capacity", sa.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("id_project", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("id_roadmap", sa.INTEGER(), autoincrement=True, nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "budget_allocation",
                sa.NUMERIC(precision=12, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "quarter", sa.VARCHAR(length=20), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("team_size", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("roadmap_id_project_fkey"),
            "project",
            ["id_project"],
            ["id_project"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("id_company")
        batch_op.drop_column("role")
        batch_op.drop_column("email")
        batch_op.drop_column("name")
        batch_op.drop_column("id_profile")

    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "project_name",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "id_project",
                sa.INTEGER(),
                server_default=sa.text("nextval('project_id_project_seq'::regclass)"),
                autoincrement=True,
                nullable=False,
            )
        )
        batch_op.drop_constraint("profile_id_company_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("project_id_company_fkey"),
            "company",
            ["id_company"],
            ["id_company"],
        )
        batch_op.drop_constraint("profile_email_key", type_="unique")
        batch_op.drop_column("role")
        batch_op.drop_column("email")
        batch_op.drop_column("name")
        batch_op.drop_column("id_profile")

    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "createdat",
                postgresql.TIMESTAMP(),
                server_default=sa.text("now()"),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "email", sa.VARCHAR(length=255), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "role", sa.VARCHAR(length=100), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("id_profile", sa.INTEGER(), autoincrement=True, nullable=False)
        )
        batch_op.create_foreign_key(
            batch_op.f("profile_id_company_fkey"),
            "company",
            ["id_company"],
            ["id_company"],
            ondelete="SET NULL",
        )
        batch_op.create_unique_constraint(
            batch_op.f("profile_email_key"),
            ["email"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.alter_column(
            "id_company", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )
        batch_op.drop_column("company_name")

    with op.batch_alter_table("milestone", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("end_date", sa.DATE(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "status", sa.VARCHAR(length=50), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("goal", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("id_milestone", sa.INTEGER(), autoincrement=True, nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("milestone_id_roadmap_fkey"),
            "roadmap",
            ["id_roadmap"],
            ["id_roadmap"],
            ondelete="CASCADE",
        )
        batch_op.alter_column(
            "id_roadmap", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )
        batch_op.drop_column("createdat")
        batch_op.drop_column("budget_allocation")
        batch_op.drop_column("sprint_capacity")
        batch_op.drop_column("team_size")
        batch_op.drop_column("quarter")
        batch_op.drop_column("id_project")

    with op.batch_alter_table("features_ideas", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "gains",
                sa.NUMERIC(precision=10, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "id_feature",
                sa.INTEGER(),
                server_default=sa.text(
                    "nextval('features_ideas_id_feature_seq'::regclass)"
                ),
                autoincrement=True,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "business_value",
                sa.NUMERIC(precision=10, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "quality_score",
                sa.NUMERIC(precision=5, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "costs",
                sa.NUMERIC(precision=10, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "churn_opex",
                sa.NUMERIC(precision=10, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "validation_stage",
                sa.VARCHAR(length=100),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "name_feature",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "market_value",
                sa.NUMERIC(precision=10, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "opp_cost",
                sa.NUMERIC(precision=10, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_constraint("project_id_company_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("features_ideas_id_project_fkey"),
            "project",
            ["id_project"],
            ["id_project"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("features_ideas_id_company_fkey"),
            "company",
            ["id_company"],
            ["id_company"],
            ondelete="CASCADE",
        )
        batch_op.alter_column(
            "id_project", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )
        batch_op.drop_column("project_name")

    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("attachment_url", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "source", sa.VARCHAR(length=255), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "type", sa.VARCHAR(length=100), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "confidence_impact",
                sa.NUMERIC(precision=5, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("id_evidence", sa.INTEGER(), autoincrement=True, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("evidence_id_company_fkey"),
            "company",
            ["id_company"],
            ["id_company"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("evidence_id_feature_fkey"),
            "features_ideas",
            ["id_feature"],
            ["id_feature"],
            ondelete="CASCADE",
        )
        batch_op.alter_column("id_company", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "id_feature", existing_type=sa.String(), type_=sa.INTEGER(), nullable=True
        )
        batch_op.drop_column("createdat")
        batch_op.drop_column("quality_score")
        batch_op.drop_column("ttv_weeks")
        batch_op.drop_column("ttbv_weeks")
        batch_op.drop_column("ttm_weeks")
        batch_op.drop_column("roi_percent")
        batch_op.drop_column("expected_profit")
        batch_op.drop_column("horizon")
        batch_op.drop_column("other_costs")
        batch_op.drop_column("opex_hours")
        batch_op.drop_column("investment_hours")
        batch_op.drop_column("cost_savings")
        batch_op.drop_column("revenue")
        batch_op.drop_column("name_feature")
        batch_op.drop_column("id_project")

    with op.batch_alter_table("decision_history", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "decision_text_yes_no", sa.BOOLEAN(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("id_decision", sa.INTEGER(), autoincrement=True, nullable=False)
        )
        batch_op.add_column(
            sa.Column("id_profile", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.drop_constraint("features_ideas_id_project_fkey", type_="foreignkey")
        batch_op.drop_constraint("features_ideas_id_company_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("decision_history_id_feature_fkey"),
            "features_ideas",
            ["id_feature"],
            ["id_feature"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("decision_history_id_profile_fkey"),
            "profile",
            ["id_profile"],
            ["id_profile"],
            ondelete="SET NULL",
        )
        batch_op.alter_column(
            "id_feature", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )
        batch_op.drop_column("createdat")
        batch_op.drop_column("quality_score")
        batch_op.drop_column("validation_stage")
        batch_op.drop_column("business_value")
        batch_op.drop_column("market_value")
        batch_op.drop_column("opp_cost")
        batch_op.drop_column("churn_opex")
        batch_op.drop_column("costs")
        batch_op.drop_column("gains")
        batch_op.drop_column("id_project")
        batch_op.drop_column("id_company")
        batch_op.drop_column("name_feature")

    with op.batch_alter_table("confidence_history", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "new_value",
                sa.NUMERIC(precision=5, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "old_value",
                sa.NUMERIC(precision=5, scale=2),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("id_feature", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("id_confidence", sa.INTEGER(), autoincrement=True, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("confidence_history_id_feature_fkey"),
            "features_ideas",
            ["id_feature"],
            ["id_feature"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("createdat")
        batch_op.drop_column("project_name")
        batch_op.drop_column("id_company")
        batch_op.drop_column("id_project")

    # ### end Alembic commands ###
