"""add ttm/ttbv min/max columns to Features_ideas

Revision ID: e95b1ece6168
Revises: 
Create Date: 2025-12-02 23:53:18.557567

"""
from alembic import op
import sqlalchemy as sa
# U had ook postgresql nodig, maar we houden de import nu minimalistisch
# Als u specifieke PostgreSQL-typen (zoals postgresql.TIMESTAMP) later nodig heeft, 
# kunt u 'from sqlalchemy.dialects import postgresql' toevoegen.


# revision identifiers, used by Alembic.
revision = 'e95b1ece6168'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Voeg de vier nieuwe kolommen toe aan features_ideas
    with op.batch_alter_table('features_ideas', schema='public') as batch_op:
        batch_op.add_column(sa.Column('ttm_low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ttm_high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ttbv_low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ttbv_high', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Verwijder de vier kolommen in de downgrade
    with op.batch_alter_table('features_ideas', schema='public') as batch_op:
        batch_op.drop_column('ttbv_high')
        batch_op.drop_column('ttbv_low')
        batch_op.drop_column('ttm_high')
        batch_op.drop_column('ttm_low')
        
    # ### end Alembic commands ###